GameWeb/Controllers/UsersManagementController.cs
using GameWeb.Data;
using GameWeb.Models;
using GameWeb.Models.ViewModels;
using GameWeb.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameWeb.Controllers
{
    [Authorize(Roles = RoleNames.AdminRole)]
    public class UsersManagementController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersManagementController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        #region GET
        public async Task<IActionResult> Index()
        {
            var list = _userManager.Users;

            foreach (var user in list)
            {
                var role = await _userManager.GetRolesAsync(user);
                user.Role = role.FirstOrDefault();
            }

            return View(list);
        }

        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _db.ApplicationUser.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _db.ApplicationUser.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            var objViewModel = new UserEditViewModel
            {
                Id = obj.Id,
                UserName = obj.UserName,
                Email = obj.Email,
                BirthDate = obj.BirthDate,
                Description = obj.Description,
                RoleList = RolesList()
            };

            var userRole = await _userManager.GetRolesAsync(obj);

            if (userRole.Count == 0)
            {
                objViewModel.SelectedRole = "0";
            }
            else
            {
                objViewModel.SelectedRole = userRole[0];
            }

            return View(objViewModel);
        }

        #endregion

        #region POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);

            var user = _db.ApplicationUser.Find(id);

            if (id == currentUser.Id)
            {
                ModelState.AddModelError(string.Empty, "Nie możesz usunąć własnego konta w ten sposób!");
                return View("Delete", user);
            }

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Nie znaleziono użytkownika");
                return View();
            }
            else
            {
                var userComments = _db.GameComment.Where(comment => comment.AuthorID == user.Id);

                foreach (var comment in userComments)
                {
                    comment.AuthorID = null;
                }

                var news = _db.News.Where(n => n.AuthorID == user.Id);

                foreach (var n in news)
                {
                    n.AuthorID = null;
                }

                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel obj)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(obj.Id);

                if (_db.ApplicationUser.Any(u => u.NormalizedUserName == obj.UserName.ToUpper()) && _db.ApplicationUser.FirstOrDefault(u => u.NormalizedUserName == obj.UserName.ToUpper()).Id != obj.Id)
                {
                    ModelState.AddModelError(string.Empty, "Istnieje już użytkownik o takiej nazwie");
                    obj.RoleList = RolesList();
                    return View(obj);
                }

                if (_db.ApplicationUser.Any(u => u.NormalizedEmail == obj.Email.ToUpper()) && _db.ApplicationUser.FirstOrDefault(u => u.NormalizedEmail == obj.Email.ToUpper()).Id != obj.Id)
                {
                    ModelState.AddModelError(string.Empty, "Istnieje już użytkownik o takim adresie email");
                    obj.RoleList = RolesList();
                    return View(obj);
                }

                user.UserName = obj.UserName;
                user.Email = obj.Email;
                user.BirthDate = obj.BirthDate;
                user.Description = obj.Description;

                if (obj.Password != null)
                {
                    List<string> errors = new List<string>();

                    var passwordValidators = _userManager.PasswordValidators;

                    foreach (var validator in passwordValidators)
                    {
                        var result = await validator.ValidateAsync(_userManager, null, obj.Password);

                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                errors.Add(error.Description);
                            }
                        }
                    }

                    if (errors.Count > 0)
                    {
                        var message = String.Join(" ", errors.ToArray());
                        ModelState.AddModelError(string.Empty, message);
                        obj.RoleList = RolesList();
                        return View(obj);
                    }

                    await _userManager.RemovePasswordAsync(user);
                    await _userManager.AddPasswordAsync(user, obj.Password);
                }

                var userRole = await _userManager.GetRolesAsync(user);

                if (userRole.Count > 0)
                {
                    await _userManager.RemoveFromRoleAsync(user, userRole[0]);
                }

                if (obj.SelectedRole != "0")
                {
                    await _userManager.AddToRoleAsync(user, obj.SelectedRole);
                }

                await _userManager.UpdateAsync(user);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #endregion

        #region helperMethods
        private List<SelectListItem> RolesList()
        {
            return new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Brak roli",
                    Value = "0"},
                new SelectListItem
                {
                    Text = RoleNames.GamePublisherRole,
                    Value = RoleNames.GamePublisherRole
                },
                new SelectListItem
                {
                    Text = RoleNames.NewsCreatorRole,
                    Value = RoleNames.NewsCreatorRole
                },
                new SelectListItem
                {
                    Text = RoleNames.AdminRole,
                    Value = RoleNames.AdminRole
                },
            };
        }

        #endregion
    }
}

GameWeb/Views/UsersManagement/Delete.cshtml
@model GameWeb.Models.ApplicationUser

<form method="post" asp-action="DeleteUser" enctype="multipart/form-data">
    <input asp-for="Id" hidden />
    <div>
        <h2>Usuwanie użytkownika</h2>
        
        <div style="text-align: center; margin-top: 20px;">
            <div asp-validation-summary="ModelOnly" class="validation-error-span"></div>
            <p>Czy na pewno chcesz usunąć użytkownika <strong>@Model.UserName</strong>?</p>

            <div>
                <input type="submit" value="Usuń" class="action-button cancel-button" style="margin-right: 8px;" />
                <a asp-action="Index" class="action-button">Anuluj</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

GameWeb/Views/UsersManagement/Edit.cshtml
@model GameWeb.Models.ViewModels.UserEditViewModel
@{
    ViewData["Title"] = "Edytuj użytkownika";
}

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div>
        <div asp-validation-summary="ModelOnly" class="validation-error-span"></div>
        <div class="upper-row">
            <h2>Edytuj użytkownika</h2>
        </div>
        <div class="default-form">
            <div class="form-input-set">
                <label asp-for="UserName"></label>
                <input class="text-input" asp-for="UserName" />
                <span class="validation-error-span" asp-validation-for="UserName" />
            </div>
            <div class="form-input-set">
                <label asp-for="Email"></label>
                <input class="text-input" asp-for="Email" />
                <span class="validation-error-span" asp-validation-for="Email" />
            </div>
            <div class="form-input-set">
                <label asp-for="Password"></label>
                <input class="text-input" asp-for="Password" />
                <span class="validation-error-span" asp-validation-for="Password" />
            </div>
            <div class="form-input-set">
                <label asp-for="ConfirmPassword"></label>
                <input class="text-input" asp-for="ConfirmPassword" />
                <span class="validation-error-span" asp-validation-for="ConfirmPassword" />
            </div>
            <div class="form-input-set">
                <label asp-for="BirthDate"></label>
                <input class="text-input" asp-for="BirthDate" />
                <span class="validation-error-span" asp-validation-for="BirthDate" />
            </div>
            <div class="form-input-set">
                <label asp-for="Description"></label>
                <textarea class="text-input" rows="6" asp-for="Description"></textarea>
                <span class="validation-error-span" asp-validation-for="Description" />
            </div>
            <div>
                <label>Rola</label>
                <select asp-for="SelectedRole" asp-items="@Model.RoleList" class="select-input">
                    Wybierz rolę
                </select>
            </div>
        </div>
        <div class="form-buttons-row">
            <input type="submit" value="Zatwierdź" class="action-button add-button" />
            <a asp-action="Index" class="action-button cancel-button">Anuluj</a>
        </div>

    </div>
</form>

GameWeb/Views/UsersManagement/Index.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewBag.Title = "Wszyscy użytkownicy";
}

<h1>Wszyscy użytkownicy</h1>

@if (Model.Any())
{
    <div class="table-container">
        <table>
            <tr>
                <th>Nazwa użytkownika</th>
                <th>Email</th>
                <th>Rola</th>
                <th></th>
            </tr>
            @foreach (var user in Model)
            {
                <tr>
                    <td>
                        @user.UserName
                    </td>
                    <td>
                        @user.Email
                    </td>
                    <td>
                        @user.Role
                    </td>
                    <td>
                        <div class="action-buttons">
                          <a asp-controller="UsersManagement" asp-route-id="@user.Id" asp-action="Edit" class="btn btn-info"><i class="fas fa-edit"></i></a>
                          <a asp-controller="UsersManagement" asp-route-Id="@user.Id" asp-action="Delete" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
}
else
{
    <p>Brak użytkowników.</p>
}